Algoritmo "Exibir mensagem"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson
// Descrição   : Exibir uma mensagem
// Autor(a)    : Beatriz Romão
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Beatriz - São Paulo")
Escreval ("Equipe 04")
Escreval ("Jailson")

Fimalgoritmo